#server.port=8001
#
#spring.application.name=service-edu
#
#spring.profiles.active=dev
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/moon?serverTimezone=GMT%2b8
#spring.datasource.data-username=root
#spring.datasource.password=root
#
#mybatis-plus.check-config-location.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081

spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moon?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
